### PR TITLE
Fix failed to parse source map error (#42)

### LINKED ISSUE #42: Failed to parse source map - Error: ENOENT: no such file or directory
I've added the dependency: `npm i @metamask/detect-provider`

But getting this error:

```
Failed to parse source map from '/home/pomatti/pjs/uniswap/uniswap-widget/node_modules/@metamask/detect-provider/src/index.ts' file: Error: ENOENT: no such file or directory, open '/home/pomatti/pjs/uniswap/uniswap-widget/node_modules/@metamask/detect-provider/src/index.ts'
```

Only thing I'm doing is importing it:

```js
import detectEthereumProvider from '@metamask/detect-provider';
```

No idea why it is complaining:

image

### PR DESCRIPTION
**Pull request by maui-r**
Fix #42 as proposed by @mcmire

### CODE REVIEW

**Comment by mcmire** [comment]
Hey @maui-r, sorry I haven't looked at this yet. I need to double-check this against `create-react-app` to verify that the issue reported is indeed resolved. I'll make time for this today.

**Review by mcmire — APPROVED** [review]
Okay, I went through the same steps as given [here](https://github.com/MetaMask/detect-provider/issues/42#issuecomment-1082787562) and can confirm that I no longer see an error. Thanks for this fix!

**Comment by mcmire** [comment]
I'm working on creating a new release which includes this fix. I need to get https://github.com/MetaMask/detect-provider/pull/47 merged but then I will get a new release issued after that.

**Review by meny3437-blip — COMMENTED** [review]
npm i @metamask/detect-provider meny3437-blip

**Review by meny3437-blip — COMMENTED** [review]
npm i @metamask/detect-provider meny3437-blip

**Pull request merged**
