### PR TITLE
Removes global Window types

### PR DESCRIPTION
**Pull request by dckesler**

### CODE REVIEW

**Comment by rekmarks** [comment]
@dckesler thank you for your contribution! Can you please provide some context for these changes?

**Comment by dckesler** [comment]
> @dckesler thank you for your contribution! Can you please provide some context for these changes?

Yes! Sorry I had meant to add more to the PR before I made it but oh well. In our library we have our own `ethereum` type on the global window that has a bunch of things not included with the ethereum global in here. This change still lets `detect-provider` have the Window types it needs while letting other consumers of this library have their own ethereum global.

**Comment by dckesler** [comment]
Also, I hadn't realized I was behind main so it added a merge commit. I can remove that if you'd prefer.

**Comment by syffs** [comment]
this `window.ethereum` typing definition makes no sense. It's not even compatible `MetaMaskInpageProvider`

**Comment by rubenswieringa** [comment]
I’d agree with the changes in this PR; a package is not supposed to put typing-restrictions on a global variable on the Window-object. On top of that it looks like the package works fine just casting the Window-object in-place, correct?

@rekmarks can we get an update on what’s happening with this PR?

**Review by rekmarks — APPROVED** [review]
Yes, this is fine. My apologies for the delay.

**Pull request merged**
